5th task fixes; 6th task implemented
js-tasks-ru/js-20221021_egort pull request #6
Opened 2022-11-10 14:19 UTC by EgorTglhf

2022-11-10 14:20 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-10 21:33 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-11 14:38 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +    this.subElements.header.addEventListener('pointerdown', (event) => {
👍 good 
лайк за использование `event-delegation`

2022-11-11 14:38 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +        this.element.style.left = 30 + event.pageX - this.element.offsetWidth / 2 + 'px';
30 следует вынести в переменную

2022-11-11 14:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener('pointerover', (event) => {
а как Вы планируете удалить данный обработчик?

2022-11-11 14:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    let tooltipElem = document.createElement('div');
`const`

2022-11-11 14:39 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      const onMouseMove = (event) => {
это следует вынести в отдельный метод

2022-11-11 14:40 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    this.remove();
а где удаление обработчика `pointerover`?

2022-11-11 14:40 UTC, dosandk requested changes
решение `Tooltip` следует поправить

2022-11-11 15:20 UTC, EgorTglhf commented on 06-events-practice/2-tooltip/index.js
> +      const onMouseMove = (event) => {
следует вынести onMouseMove в отдельный метод? в таком случае придется заменить this. на Tooltip.instance. , верно понимаю?
а остальные функции, которые вешаются на обработчики событий тоже? onMouseOut и новая onMouseOver

2022-11-11 15:32 UTC, EgorTglhf commented on 06-events-practice/2-tooltip/index.js
> +      const onMouseMove = (event) => {
вместо замены this. на Tooltip.instance. следует воспользоваться .bind(this)?

2022-11-11 17:28 UTC, EgorTglhf commented on 06-events-practice/2-tooltip/index.js
> +      const onMouseMove = (event) => {
после разбора задания на уроке, вопросы отпали

2022-11-11 19:39 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-11-11 19:41 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-11-14 12:15 UTC, jsru commented
Проверьте, пожалуйста, ваше решение, не все тесты прошли (PR не будет принят до тех пор, пока **все** добавленные задачи не будут решены).

2022-11-14 12:16 UTC, EgorTglhf commented
На данный момент не понимаю как довести doubleSlider до конца. чтобы проходил все тесты.
Уперся в правильный расчет % смещения ползунков. В тестах слайдера нет и его длина 0.

2022-11-14 14:51 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +      const onMouseMove = (event) => {
👍 good

2022-11-14 14:52 UTC, dosandk commented
@EgorTglhf отправляйте PR с DoubleSlider, я посмотрю что с тестами

2022-11-14 14:53 UTC, dosandk commented on 06-events-practice/1-sortable-table-v2/index.js
> +  sortOnClient(field, direction = 'asc') {
👍 good

2022-11-14 14:53 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.addEventListener('pointermove', this.onMouseMove);
👍 good

2022-11-14 14:53 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +  constructor() {
👍 good

2022-11-14 14:53 UTC, dosandk commented on 06-events-practice/2-tooltip/index.js
> +    document.removeEventListener('pointerover', this.onMouseOver);
👍 good

2022-11-14 14:56 UTC, dosandk commented on 06-events-practice/3-double-slider/index.js
> +  onMouseDown = (event) => {
а посмотрите вот на это решение https://github.com/dosandk/js-20221021/tree/master/05-events-practice/3-double-slider/solution
если не поможет - напишите мне в Discord

2022-11-14 14:56 UTC, dosandk approved these changes
good 👍

2022-11-14 14:57 UTC, merged